include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  exclude:
    - build/**
    - "*/**.config.dart"
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false