name: todo_app_backend
description: Todo App Backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.6.0
  in_memory_todos_data_source:
    path: packages/in_memory_todos_data_source
  postgres: ^2.5.2
  todos_data_source:
    path: packages/todos_data_source

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
