name: todo_app_backend
description: Todo App Backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.6.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  in_memory_todos_data_source:
    path: packages/in_memory_todos_data_source
  injectable: ^2.1.0
  postgres: ^2.5.2
  todos_data_source:
    path: packages/todos_data_source

dev_dependencies:
  build_runner: ^2.3.2
  injectable_generator: ^2.1.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
